version: '3.6'  
services:
  rabbitmq:
   image: rabbitmq:3-management
   ports:
      # The standard AMQP protocol port
      - '5673:5673'
      # HTTP management UI
      - '15673:15673'
   networks:
      - network
   container_name: rabbitmq
   restart: 'always'

  consumer:
   build:
      context: ./consumer
   container_name: bot_consumer
   networks:
      - network
   environment:
      - RABBITMQ_HOST=rabbitmq
   depends_on:
      - rabbitmq

  publisher:
   build:
     context: ./publisher
   container_name: bot_publisher
   environment:
      - RABBITMQ_HOST=rabbitmq
   depends_on:
      - rabbitmq   
   networks:
      - network
networks:
  network: {}
